### ISSUE TITLE
Uppercase characters in requested repo names are rejected as invalid

### ISSUE THREAD

**Issue by agross** [qoomon/github-actions-access-manager#11]
`foo/bar` as a repo name works, `Foo/bar` does not because [this regex](https://github.com/qoomon/github-actions-access-manager/blob/03cd92b877e901b166873cb48378cc11400a79dc/server/api/index.js#L154C12-L154C71) does not match uppercase chars.

**Comment by qoomon** [comment]
thanks for reporting. should be fixed.

**Comment by agross** [comment]
Thanks! Now if only I could authenticate against GH packages with an obtained token from your app. It seems like a limitation that only Personal Access Tokens work.

**Comment by qoomon** [comment]
@agross I'll check this, it should work actually
