### ISSUE TITLE
Granting `pull-requests` scope fails due to `isValidPermission` in App Server.

### ISSUE THREAD

**Issue by hitsumabushi845** [qoomon/github-actions-access-manager#14]
Hi, I am using this action to manage access to my organization's repository.

Now I am facing the problem described in this title.
I want to grant `pull-requests:write` permission, but the token creation workflow fails because the `isValidPermission` in App Server fails with regular expressions.
https://github.com/qoomon/github-actions-access-manager/blob/main/server/api/index.js#L146-L147

Is this behavior expected? Please let me know if I am incorrect in specifying the scope of the permission.

**Comment by hitsumabushi845** [comment]
GitHub API accepts `pull_requests`, but underscore also not contained the regexp.

**Comment by qoomon** [comment]
that is a bug :-) I'll fix it.
FYI I'm working on a complete rewrite of the access manager. It will probably released next month.

**Comment by qoomon** [comment]
Should be fixed
