### ISSUE TITLE
Clarify example usage to follow blue/green in architecture diagram

### ISSUE THREAD

**Issue by NickCrews** [qoomon/github-actions-access-manager#2]
Hi! First of all, thanks for this, it looks brilliant and hopefully will really be exactly what I need.

In the `Usage` section of the readme, it says things like "Create .github/access.yaml file", but it doesn't say in which repo to do all these steps. Can you clarify this section to specify either green or blue repo, following the architecture diagram at the top? That architecture walkthrough was super helpful, so I think you could leverage it more.

**Comment by qoomon** [comment]
Hi, thanks for the feedback. I'll try to add some visualisation. I'll keep you posted.
