### ISSUE TITLE
BUG: Actual release still uses outdated GITHUB_ACCESS_TOKEN

### ISSUE THREAD

**Issue by NickCrews** [qoomon/github-actions-access-manager#5]
The source file uses the new name for the env variable, GITHUB_ACCESS_MANAGER_TOKEN:

https://github.com/qoomon/github-actions-access-manager/blob/58182cee606d4d77c68f41826fb28f2a7c4e3d58/index.js#L29

But the dist version isn't up to date, still uses GITHUB_ACCESS_TOKEN:

https://github.com/qoomon/github-actions-access-manager/blob/6f9513b8361b8fd8c748e2d3b2b4cd8c274079bb/dist/index.js#L2833

This makes it so the example in the readme, `git clone https://_:$GITHUB_ACCESS_MANAGER_TOKEN@github.com/example/test.git`, doesn't work.

**Comment by qoomon** [comment]
oh thanks so much I'll fix it today.

**Comment by qoomon** [comment]
fixed
